### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by louiiuol** [louiiuol/lmc-ui#3]
# Context 📝

_This issue represents the state of design of the wireframes for all UIs projects (public, user, & admin pages)_

_These wireframes only specify how big sections should be displayed, in order to save time, content and the graphical chart will not be present: **only layout matters at this point**_

# TODO 💪

- [ ] Design wireframes for
  - [ ] Public Landing page
  - [ ] User logged-in space
  - [ ] Admin back-office

# Sources 🔗

- [ ] [Figma Wireframes UI](https://www.figma.com/file/d9ZMamk2FZPuhOqN9qVWES/clairess-methood-schema?node-id=0%3A1&t=BJcdQrbSjoVNbQjb-0)
